### ISSUE TITLE
Cocoapods and CoreData support

### ISSUE THREAD

**Issue by HelloRyanCR7** [JARMourato/Kodable#22]
Original request: 

- How to use it in conjunction with CoreData to directly convert JSON data into a new CoreData Entity or update the original Entity. And hope to support CocoaPods

**Comment by JARMourato** [comment]
Hey @HelloRyanCR7 thank you for interest in Kodable. 

*Short answer is: There's no support for CoreData nor Cocoapods at the moment.* 

### Cocoapods
There are no plans to support it, in fact it was not added on purpose. Moving forward, I believe SPM with be the main source for 3rd party libraries, thus adding support for Cocoapods is not on the roadmap. In any case, you can use SPM and Cocoapods in the same project :) So you can still use Kodable. 


### CoreData
Supporting CoreData (or any other ORM/database) is a bit out of scope of this library. You can probably build your own add on to achieve that functionality. If I recall correctly, CoreData support the `set(value: forKey:)` api. With a bit of work, perhaps with the help of some reflection libraries, you can get to this functionality, where any `Codable` object can be converted in a CoreData Object. 

Given the aforementioned reasons, I'll be closing the issue. 

Nevertheless, any questions are welcomed! 

Thank you
