### ISSUE TITLE
Optional parameters with nil values are encoded as nulls

### ISSUE THREAD

**Issue by rogerluan** [JARMourato/Kodable#6]
Hey 👋 

While using this framework I found that when encoding optional parameters that have a nil value, those values translate to `null` values in the resulting JSON, instead of skipping them (as the native `Encodable` would). This becomes a problem when submitting such JSONs to PATCH endpoints, as the absence of a key-value pair and the presence of the key with a null value have different meanings.

Is there any way to circumvent this that I missed, or is this a bug that needs to be addressed still? 🙏 

Looking forward to hearing from you and to continuing using Kodable 🚀

**Comment by JARMourato** [comment]
I intended to follow `Encodable` as much as possible. Thus, this behavior should be changed. would you value the option to encode as `null`? That could be an option

**Comment by rogerluan** [comment]
Yes, I think it could be an option. Idk how this could work, but something along the lines of:

```
@Coding("my_key", encodeAsNullIfNil: true) // Defaults to false if omitted 
```

There're cases where encoding null would be very useful 🙏
